language: java
jdk:
  - openjdk6
script: "./travis.sh"
after_success:
  - curl "-F plugin=@silex-plugin.zip http://silex.sorien.sk/deploy/$TRAVIS_BRANCH/$UUID"
  - bash <(curl -s https://codecov.io/bash)
